<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: api.proto

namespace ZMDev\FateSDK\Pb;

use Google\Protobuf\Internal\GPBType;
use Google\Protobuf\Internal\RepeatedField;
use Google\Protobuf\Internal\GPBUtil;

/**
 * Generated from protobuf message <code>ZMDev.FateSDK.pb.AppListReq</code>
 */
class AppListReq extends \Google\Protobuf\Internal\Message
{
    /**
     * Generated from protobuf field <code>.ZMDev.FateSDK.pb.UserID user_id = 1;</code>
     */
    private $user_id = null;
    /**
     * Generated from protobuf field <code>int32 per_page = 2;</code>
     */
    private $per_page = 0;
    /**
     * Generated from protobuf field <code>int32 page = 3;</code>
     */
    private $page = 0;

    public function __construct() {
        \GPBMetadata\Api::initOnce();
        parent::__construct();
    }

    /**
     * Generated from protobuf field <code>.ZMDev.FateSDK.pb.UserID user_id = 1;</code>
     * @return \ZMDev\FateSDK\Pb\UserID
     */
    public function getUserId()
    {
        return $this->user_id;
    }

    /**
     * Generated from protobuf field <code>.ZMDev.FateSDK.pb.UserID user_id = 1;</code>
     * @param \ZMDev\FateSDK\Pb\UserID $var
     * @return $this
     */
    public function setUserId($var)
    {
        GPBUtil::checkMessage($var, \ZMDev\FateSDK\Pb\UserID::class);
        $this->user_id = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>int32 per_page = 2;</code>
     * @return int
     */
    public function getPerPage()
    {
        return $this->per_page;
    }

    /**
     * Generated from protobuf field <code>int32 per_page = 2;</code>
     * @param int $var
     * @return $this
     */
    public function setPerPage($var)
    {
        GPBUtil::checkInt32($var);
        $this->per_page = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>int32 page = 3;</code>
     * @return int
     */
    public function getPage()
    {
        return $this->page;
    }

    /**
     * Generated from protobuf field <code>int32 page = 3;</code>
     * @param int $var
     * @return $this
     */
    public function setPage($var)
    {
        GPBUtil::checkInt32($var);
        $this->page = $var;

        return $this;
    }

}

