<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: api.proto

namespace ZMDev\FateSDK\Pb;

/**
 * Protobuf enum <code>ZMDev\FateSDK\Pb\CertificateType</code>
 */
class CertificateType
{
    /**
     * Generated from protobuf enum <code>StudentNum = 0;</code>
     */
    const StudentNum = 0;
}

