<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: api.proto

namespace ZMDev\FateSDK\Pb;

use Google\Protobuf\Internal\GPBType;
use Google\Protobuf\Internal\RepeatedField;
use Google\Protobuf\Internal\GPBUtil;

/**
 * Generated from protobuf message <code>ZMDev.FateSDK.pb.LoginCheckRes</code>
 */
class LoginCheckRes extends \Google\Protobuf\Internal\Message
{
    /**
     * Generated from protobuf field <code>bool is_login = 1;</code>
     */
    private $is_login = false;

    public function __construct() {
        \GPBMetadata\Api::initOnce();
        parent::__construct();
    }

    /**
     * Generated from protobuf field <code>bool is_login = 1;</code>
     * @return bool
     */
    public function getIsLogin()
    {
        return $this->is_login;
    }

    /**
     * Generated from protobuf field <code>bool is_login = 1;</code>
     * @param bool $var
     * @return $this
     */
    public function setIsLogin($var)
    {
        GPBUtil::checkBool($var);
        $this->is_login = $var;

        return $this;
    }

}

