<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: api.proto

namespace ZMDev\Fate\Pb;

use Google\Protobuf\Internal\GPBType;
use Google\Protobuf\Internal\RepeatedField;
use Google\Protobuf\Internal\GPBUtil;

/**
 * Generated from protobuf message <code>ZMDev.Fate.pb.Application</code>
 */
class Application extends \Google\Protobuf\Internal\Message
{
    /**
     * Generated from protobuf field <code>int32 id = 1;</code>
     */
    private $id = 0;
    /**
     * Generated from protobuf field <code>string logo_hash = 2;</code>
     */
    private $logo_hash = '';
    /**
     * Generated from protobuf field <code>int64 user_id = 3;</code>
     */
    private $user_id = 0;
    /**
     * Generated from protobuf field <code>string secret = 4;</code>
     */
    private $secret = '';
    /**
     * Generated from protobuf field <code>string url = 5;</code>
     */
    private $url = '';
    /**
     * Generated from protobuf field <code>string name = 6;</code>
     */
    private $name = '';
    /**
     * Generated from protobuf field <code>string description = 7;</code>
     */
    private $description = '';
    /**
     * Generated from protobuf field <code>string redirect_url = 8;</code>
     */
    private $redirect_url = '';
    /**
     * Generated from protobuf field <code>bool revoked = 9;</code>
     */
    private $revoked = false;
    /**
     * Generated from protobuf field <code>int64 created_at = 10;</code>
     */
    private $created_at = 0;
    /**
     * Generated from protobuf field <code>int64 updated_at = 11;</code>
     */
    private $updated_at = 0;
    /**
     * Generated from protobuf field <code>int64 deleted_at = 12;</code>
     */
    private $deleted_at = 0;

    public function __construct() {
        \GPBMetadata\Api::initOnce();
        parent::__construct();
    }

    /**
     * Generated from protobuf field <code>int32 id = 1;</code>
     * @return int
     */
    public function getId()
    {
        return $this->id;
    }

    /**
     * Generated from protobuf field <code>int32 id = 1;</code>
     * @param int $var
     * @return $this
     */
    public function setId($var)
    {
        GPBUtil::checkInt32($var);
        $this->id = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>string logo_hash = 2;</code>
     * @return string
     */
    public function getLogoHash()
    {
        return $this->logo_hash;
    }

    /**
     * Generated from protobuf field <code>string logo_hash = 2;</code>
     * @param string $var
     * @return $this
     */
    public function setLogoHash($var)
    {
        GPBUtil::checkString($var, True);
        $this->logo_hash = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>int64 user_id = 3;</code>
     * @return int|string
     */
    public function getUserId()
    {
        return $this->user_id;
    }

    /**
     * Generated from protobuf field <code>int64 user_id = 3;</code>
     * @param int|string $var
     * @return $this
     */
    public function setUserId($var)
    {
        GPBUtil::checkInt64($var);
        $this->user_id = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>string secret = 4;</code>
     * @return string
     */
    public function getSecret()
    {
        return $this->secret;
    }

    /**
     * Generated from protobuf field <code>string secret = 4;</code>
     * @param string $var
     * @return $this
     */
    public function setSecret($var)
    {
        GPBUtil::checkString($var, True);
        $this->secret = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>string url = 5;</code>
     * @return string
     */
    public function getUrl()
    {
        return $this->url;
    }

    /**
     * Generated from protobuf field <code>string url = 5;</code>
     * @param string $var
     * @return $this
     */
    public function setUrl($var)
    {
        GPBUtil::checkString($var, True);
        $this->url = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>string name = 6;</code>
     * @return string
     */
    public function getName()
    {
        return $this->name;
    }

    /**
     * Generated from protobuf field <code>string name = 6;</code>
     * @param string $var
     * @return $this
     */
    public function setName($var)
    {
        GPBUtil::checkString($var, True);
        $this->name = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>string description = 7;</code>
     * @return string
     */
    public function getDescription()
    {
        return $this->description;
    }

    /**
     * Generated from protobuf field <code>string description = 7;</code>
     * @param string $var
     * @return $this
     */
    public function setDescription($var)
    {
        GPBUtil::checkString($var, True);
        $this->description = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>string redirect_url = 8;</code>
     * @return string
     */
    public function getRedirectUrl()
    {
        return $this->redirect_url;
    }

    /**
     * Generated from protobuf field <code>string redirect_url = 8;</code>
     * @param string $var
     * @return $this
     */
    public function setRedirectUrl($var)
    {
        GPBUtil::checkString($var, True);
        $this->redirect_url = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>bool revoked = 9;</code>
     * @return bool
     */
    public function getRevoked()
    {
        return $this->revoked;
    }

    /**
     * Generated from protobuf field <code>bool revoked = 9;</code>
     * @param bool $var
     * @return $this
     */
    public function setRevoked($var)
    {
        GPBUtil::checkBool($var);
        $this->revoked = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>int64 created_at = 10;</code>
     * @return int|string
     */
    public function getCreatedAt()
    {
        return $this->created_at;
    }

    /**
     * Generated from protobuf field <code>int64 created_at = 10;</code>
     * @param int|string $var
     * @return $this
     */
    public function setCreatedAt($var)
    {
        GPBUtil::checkInt64($var);
        $this->created_at = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>int64 updated_at = 11;</code>
     * @return int|string
     */
    public function getUpdatedAt()
    {
        return $this->updated_at;
    }

    /**
     * Generated from protobuf field <code>int64 updated_at = 11;</code>
     * @param int|string $var
     * @return $this
     */
    public function setUpdatedAt($var)
    {
        GPBUtil::checkInt64($var);
        $this->updated_at = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>int64 deleted_at = 12;</code>
     * @return int|string
     */
    public function getDeletedAt()
    {
        return $this->deleted_at;
    }

    /**
     * Generated from protobuf field <code>int64 deleted_at = 12;</code>
     * @param int|string $var
     * @return $this
     */
    public function setDeletedAt($var)
    {
        GPBUtil::checkInt64($var);
        $this->deleted_at = $var;

        return $this;
    }

}

