<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: api.proto

namespace ZMDev\Fate\Pb;

/**
 * Protobuf enum <code>ZMDev\Fate\Pb\CertificateType</code>
 */
class CertificateType
{
    /**
     * Generated from protobuf enum <code>StudentNum = 0;</code>
     */
    const StudentNum = 0;
    /**
     * Generated from protobuf enum <code>PhoneNum = 1;</code>
     */
    const PhoneNum = 1;
    /**
     * Generated from protobuf enum <code>Email = 2;</code>
     */
    const Email = 2;
}

