<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: api.proto

namespace ZMDev\Fate\Pb;

use Google\Protobuf\Internal\GPBType;
use Google\Protobuf\Internal\RepeatedField;
use Google\Protobuf\Internal\GPBUtil;

/**
 * Generated from protobuf message <code>ZMDev.Fate.pb.User</code>
 */
class User extends \Google\Protobuf\Internal\Message
{
    /**
     * Generated from protobuf field <code>string account = 1;</code>
     */
    private $account = '';
    /**
     * Generated from protobuf field <code>.ZMDev.Fate.pb.CertificateType certificate_type = 3;</code>
     */
    private $certificate_type = 0;
    /**
     * Generated from protobuf field <code>string password = 2;</code>
     */
    private $password = '';

    public function __construct() {
        \GPBMetadata\Api::initOnce();
        parent::__construct();
    }

    /**
     * Generated from protobuf field <code>string account = 1;</code>
     * @return string
     */
    public function getAccount()
    {
        return $this->account;
    }

    /**
     * Generated from protobuf field <code>string account = 1;</code>
     * @param string $var
     * @return $this
     */
    public function setAccount($var)
    {
        GPBUtil::checkString($var, True);
        $this->account = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>.ZMDev.Fate.pb.CertificateType certificate_type = 3;</code>
     * @return int
     */
    public function getCertificateType()
    {
        return $this->certificate_type;
    }

    /**
     * Generated from protobuf field <code>.ZMDev.Fate.pb.CertificateType certificate_type = 3;</code>
     * @param int $var
     * @return $this
     */
    public function setCertificateType($var)
    {
        GPBUtil::checkEnum($var, \ZMDev\Fate\Pb\CertificateType::class);
        $this->certificate_type = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>string password = 2;</code>
     * @return string
     */
    public function getPassword()
    {
        return $this->password;
    }

    /**
     * Generated from protobuf field <code>string password = 2;</code>
     * @param string $var
     * @return $this
     */
    public function setPassword($var)
    {
        GPBUtil::checkString($var, True);
        $this->password = $var;

        return $this;
    }

}

